### ISSUE TITLE
no file named 1.cns.out

### ISSUE THREAD

**Issue by aureliendejode** [skoren/ArrowGrid#10] opened 2021-06-04 09:25 UTC
Hi,
I used arrow_grid (without the grid option because I have trouble with that one see my other Issue "Using arrow_grid on slurm") and it worked fine until I got the following error.
Here is the end of the slurm out file:
[INFO] Arrow operating on tig00067068_1:9172-9183
[INFO] Output files completed.
[INFO] Analysis completed.
[INFO] Finished.
[INFO] exiting with return code 0 in 36386.12 sec.
Computing coverage stats
Checking success
cat: *1.cns.out: Aucun fichier ou dossier de ce type
cat: *1.cns.out: Aucun fichier ou dossier de ce type
Error: 1 failed, please check 1.cns.out for errors and try again

I checked and could not find any .cns.out file.

Do you know what happened ?

Thanks

**Comment by skoren** [comment] 2021-06-04 15:07
Are you running this off grid? As it says in the readme, we've only tested on SGE/Slurm so this has had limited testing. I think the issue is the output got sent to the screen and not a log file that subsequent steps expect. I committed a fix to the repo that should address this.

**Comment by aureliendejode** [comment] 2021-06-04 15:19
Yes for this I tried to run it off grid.
Thanks

Le ven. 4 juin 2021 à 17:07, Sergey Koren ***@***.***> a
écrit :

**Closed as completed** 2021-09-21 14:34 UTC
